trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure Resource Manager'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az group create --name testing --location centralus
      az deployment group create --resource-group testing --template-file ./azure/Bicep/26-05-2025/env_module/main.bicep --parameters ./azure/Bicep/26-05-2025/env_module/main.bicepparam
      # az group delete --name testing --yes --no-wait 
    displayName: 'Deploy Bicep Template'
